language: java

jdk:
  - oraclejdk8
  - openjdk6

env:
  global:
    - REMOTE_URL=http://got5:d8885037-2ec0-405b-b26d-906c6212e70e@ondemand.saucelabs.com:80/wd/hub


matrix:
    # latest version of firefox
    - BROWSER=firefox VERSION=35
    # oldest firefox that is supported by the current firefox driver
    - BROWSER=firefox VERSION=23


addons:
  sauce_connect:
    username: "got5"
    access_key:
      secure: "d8885037-2ec0-405b-b26d-906c6212e70e"


script: mvn verify -Dtest.remoteUrl=$REMOTE_URL -Dtest.browser="$BROWSER" -Dtest.browserVersion=$VERSION
